version: "3.8"
networks:
  default:
    name: lab8-demo-net
services:
  #Filebeat container
  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: "docker.elastic.co/beats/filebeat:8.1.0"
    volumes:
      #Mount the apache2 logs into the filebeat container so we can access and index them using the filebeat
      - apachelog:/usr/local/apache2/logs/
      #Mount the filebeat configuration so users can make edit
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    restart: on-failure
    command: filebeat -d "*"
    deploy:
      mode: global
    depends_on:
      apache2: { condition: service_healthy }

  #Apache2 container
  apache2:
    container_name: apache2
    hostname: apache2
    build: ./apache2
    ports:
      - 80:80
    volumes:
      - apachelog:/usr/local/apache2/logs/

volumes:
  apachelog:
    driver: local
